[package]
name = "tinic"
version = "0.1.7-rc1"
edition = "2024"
license = "GPL-3"
description = "Tinic is a runtime for Libretro cores that abstracts the native API and provides a ready-to-use foundation for cross-platform frontends. "
keywords = ["emulator", "libretro", "tinic"]
categories = ["emulators", "libretro"]
repository = "https://github.com/Xsimple1010/Tinic"

[dependencies]
retro-core.workspace = true
retro-controllers.workspace = true
retro-video.workspace = true
retro-audio.workspace = true
libretro-sys.workspace = true
tinic-generics.workspace = true
winit.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
