[package]
name = "retro_ab"
version = "0.1.0"
edition = "2021"

[features]
core_logs = []

[dependencies]
sdl2.workspace = true
uuid.workspace = true
libretro_sys.workspace = true
generics.workspace = true
