[package]
name = "retro_core"
version = "0.1.0"
edition = "2021"

[features]
core_logs = []
core_ev_logs = []
core_full_logs = ["core_ev_logs", "core_logs"]
hw = []

[dependencies]
sdl2.workspace = true
uuid.workspace = true
libretro_sys.workspace = true
generics.workspace = true
